### ISSUE TITLE
Error: Unable to extract. Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by juancarlospaco** [dom96/choosenim#212]
```console
PS C:\Users\user> .\choosenim.exe --firstInstall stable
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: Yes
      Info: Your client ID is ad6866de-b849-4f26-9451-d3ce56f443c3
      Info: C:\Users\user\.choosenim\downloads\dlls.zip already downloaded
 Extracting dlls.zip
     Error: Unable to extract. Error was 'Cannot create a file when that file already exists.'

PS C:\Users\user>
```

I infer that if `C:\Users\user\.choosenim\downloads\dlls.zip` already exists for some reason,
it crashes complaining about the file already existing. :shrug: 
Theres no other process running so no file is locked.
It should overwrite whatever file it needs to extract. 

#### Workaround

- I manually deleted `C:\Users\user\.choosenim\` and `C:\Users\user\.nimble\` and tried again and it worked just Ok.

Windows 10, x86_64, fresh install, `0.6.0` [EXE from GitHub release.](https://github.com/dom96/choosenim/releases/tag/v0.6.0)

**Comment by dom96** [comment]
Fixed in devel. Just need a release.

**Comment by juancarlospaco** [comment]
So... it still failing as of today, if it needs a Release, do a Release,
because is still crashing on Windows with the same error.

**Comment by dom96** [comment]
How can it possibly be? This bug should only happen when DLLs have been installed into ``~/.nimble/bin``, shouldn't be possible on a fresh install.

**Comment by xflywind** [comment]
I hope a new release comming soon. I rely on `choosenim` to switch Nim versions to test my program in windows. Now I have to delete all dlls when I want to switch Nim version.

**Comment by juancarlospaco** [comment]
I hope a new release coming soon too.
